### ISSUE TITLE
Box Sync filename space screws it up 

### ISSUE THREAD

**Issue by brianmapes** [suvarchal/IDV_teleport#1]
**Because I called this from local directory /Users/bem/Box Sync/Colombia_Yepes_Work, I got this error:** 

bmapes.rsmas.miami.edu{bem} 116: python idv_teleport.py -t 2016-06-29_00:00:00 -b Colombia_teleport_template_nosoundings.xidv -td 4hours -case Colombia_2016-0629_0702_teleported

Unknown argument:/Users/bem/Box

**It's because of the space. Easily fixed?**

**Comment by suvarchal** [comment]
surprising, all calls to directory use python's os.path.join which should handle all paths accordingly 
any line number would be helpful or i could create one such spaced directory and try.

**Comment by brianmapes** [comment]
Yeah, try it with a directory name with a space in it.

I wasn’t able to rename Box_Sync without screwing up its function.


On May 26, 2017, at 5:36 AM, Suvarchal Kumar Cheedela <notifications@github.com<mailto:notifications@github.com>> wrote:


surprising, all calls to directory use python's os.path.join which should handle all paths accordingly
any line number would be helpful or i could create one such spaced directory and try.

**Comment by suvarchal** [comment]
parser didnt handle case with filenames specified with spaces in between, fixed that but another main issue stems from IDV itself which cannot open bundles or isl files with windows style filepath. 
$IDV_HOME/runIDV windows\ style\ dir/testbundle.xidv 

fixed by forcing idv to read .isl file from current directory.
